import React from 'react'
import ReactDOM from 'react-dom'
import { createStore, applyMiddleware } from 'redux';
import { Provider } from 'react-redux';
import reducers from './reducers';
import thunkMiddleware from 'redux-thunk'
import { createLogger } from 'redux-logger'
import registerServiceWorker from './registerServiceWorker';
import './index.css';
import { BrowserRouter } from 'react-router-dom'
import App from './app';

// This value is rendered into the DOM by the server
const initialState = window.__INITIAL_STATE;

// Create store with the initial state generated by the server
const reduxMiddleware = applyMiddleware(thunkMiddleware, createLogger())
// const store = createStore(reducers, initialState);
const store = createStore(reducers, initialState, reduxMiddleware);

ReactDOM.render(
  <Provider store={store}>
    <BrowserRouter>
      <App/>
    </BrowserRouter>
  </Provider>,
  document.getElementById('app')
);
registerServiceWorker();
