import React from 'react'
import { createStore, applyMiddleware, compose } from 'redux' 
import thunkMiddleware from 'redux-thunk'
import reducers from './reducers'
import { renderToString } from 'react-dom/server'
import { Provider } from 'react-redux'
import { StaticRouter } from 'react-router'
import DocumentMeta from 'react-document-meta'
import { ServerStyleSheet } from 'styled-components'

import App from './app'

const htmlToString = (store, req, context) => {
    const sheet = new ServerStyleSheet()
    const app = (
      <Provider store={store}>
        <StaticRouter
          location={req.url}
          context={context}>
            <App/>
        </StaticRouter>
      </Provider>
    )
    const body = renderToString(sheet.collectStyles(app))

    return renderToString(
       <html lang="en">
        <head>
          <meta name="viewport" content="width=device-width, initial-scale=1"/>
          

          {"{{meta}}"}
          {sheet.getStyleElement()}
          {"{{cssBundles}}"}
        </head>
        <body>
          <div id="app">
           
          </div>
          <script>{"window.__INITIAL_STATE = {{initialState}}"}</script>
          {"{{jsBundles}}"}
        </body>
        </html>
    )
}

const render = (initialState, req, res) => {
  return new Promise((resolve, reject) => {
      
    // Create store with the initial state generated by the server
    var store = createStore(  
        reducers,
        initialState,
        compose(
          applyMiddleware(thunkMiddleware)        
        )
      )
    var context = {store, promises:[]}

    //  Render the app using the context and store
    var body = htmlToString(store, req, context)

    // All components having promises are now fetching data
    Promise.all(context.promises)
      .then(() => {

        context.resolved = true 
        // Rendering AGAIN with new store. Stupid performance wise. OK for less code
        // A better way could be to use a router config as specified in react-router 4 docs
        var RenderedApp = htmlToString(store, req, context)

        // Get meta data
        const meta = DocumentMeta.renderAsHTML();
        
        var jsBundles, cssBundles
        if(process.env.NODE_ENV === "development"){
          //  Get paths to the webpack generated bundles
          const assetsByChunkName = res.locals.webpackStats.toJson().assetsByChunkName
          jsBundles = normalizeAssets(assetsByChunkName.main)
              .filter(path => path.endsWith('.js'))
              .map(path => `<script src="${path}"></script>`)
              .join('\n')
          cssBundles = normalizeAssets(assetsByChunkName.main)
              .filter(path => path.endsWith('.css'))
              .map(path => `<link rel="stylesheet" href="${path}" />`)
              .join('\n')
        }else{
          jsBundles = '<script src="/build/static/js/main.js"></script>'
          cssBundles = '<link rel="stylesheet" href="/build/static/css/main.css" />'
        }

        // Create new html
        RenderedApp = RenderedApp.replace('{{initialState}}', JSON.stringify(store.getState()))
        RenderedApp = RenderedApp.replace('{{meta}}', meta)
        RenderedApp = RenderedApp.replace('{{cssBundles}}', cssBundles)
        RenderedApp = RenderedApp.replace('{{jsBundles}}', jsBundles)

        // Serve it. Bon appetite
        resolve(RenderedApp)
      })
      .catch((err) => reject(err))
    })
} 

// This function makes server rendering of asset references consistent with different webpack chunk/entry confiugrations
function normalizeAssets(assets) {
  return Array.isArray(assets) ? assets : [assets]
}


export {render}

